### ISSUE TITLE
Cannot find module 'react-toolbox'

### ISSUE THREAD

**Issue by mrandri19** [react-toolbox/react-toolbox#1506]
Doesn't work out of the box with Typescript `2.3.3`.
I keep getting `Cannot find module 'react-toolbox'` error even though webpack compiles and the components work.
My `tsconfig`:
```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "es6",
        "target": "es6",
        "jsx": "react"
    },
    "include": [
        "./src/**/*"
    ]
}
```

My `webpack.config.js`:
```
var { resolve } = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CheckerPlugin } = require('awesome-typescript-loader')

module.exports = {
    entry: './src/index.tsx',
    output: {
        filename: 'bundle.js',
        path: resolve(__dirname, 'dist')
    },

    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx']
    },

    devtool: 'source-map',

    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: ['babel-loader', 'awesome-typescript-loader'],
                exclude: /node_modules/
            },
            {
                enforce: 'pre',
                test: /\.js$/,
                loader: "source-map-loader"
            },
            {
                enforce: 'pre',
                test: /\.tsx?$/,
                use: "source-map-loader"
            },
            {
                test: /\.css$/,
                use: [
                    'style-loader',
                    'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
                    {loader: 'postcss-loader', options: {sourceMap: true, sourceComments: true}}
                ],
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin(
            {
                hash: true,
                template: resolve(__dirname, 'src/index.html'),
                minify: {
                    collapseWhitespace: true
                }
            }
        ),
        new CheckerPlugin()
    ]
};
```

**Comment by javivelasco** [comment]
I've just released `beta.12` that fixes the issue

**Comment by mrandri19** [comment]
It didnt fix it for me, I had to change to `moduleResolution: "node"` in my `tsconfig.json` and then move the `index.d.ts` file from `node_modules/react_toolbox/src/` to `node_modules/react_toolbox/`.

**Comment by javivelasco** [comment]
Will check it again, the issue was that ts files were not being copied, now they are but maybe I missed something

**Comment by javivelasco** [comment]
That's very weird. Please ensure you removed node_modules and installed again. I've just check it and it doesn't make sense that you had to move `index.d.ts` since I've made a fresh install and it is there. If anybody else can confirm the issue that would be helpful

**Comment by mrandri19** [comment]
Ok it works now, my fault. Thanks for the help :smile:
