### ISSUE TITLE
Tabs: "Cannot read property 'getBoundingClientRect' of null"

### ISSUE THREAD

**Issue by bionikspoon** [react-toolbox/react-toolbox#1535]
## Problem

Reliably getting an error with HMR updates:`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null at Tabs.js:86`

## Context

- Version: `2.0.0-beta.8`
- Error is pointing to this line: https://github.com/react-toolbox/react-toolbox/blob/2.0.0-beta.8/components/tabs/Tabs.js#L85
- **In the inspector `this.navigationNode` equals `null`**
  - THIS IS SUPER SURPRISING since it's behind a guard clause:
    ```js
    if (this.navigationNode /* && ... */) {
      // ...
      // somehow this.navigationNode is null !!! object mutation, race condition? inside a callback?
    }
    ```
- ~~Possibly related: On my team, we're not using the component to render the content of each tab (`props.children` of `<Tab />` is undefined). We're only using it for the navigation and we handle displaying tab content somewhere else.  Not sure if this is totally relevant.~~

## Possible Solutions

Pull `this.navigationNode` into a variable. 

### From
```js
    updatePointer = (idx) => {
      if (this.navigationNode && this.navigationNode.children[idx]) {
        requestAnimationFrame(() => {
          const nav = this.navigationNode.getBoundingClientRect();
          const label = this.navigationNode.children[idx].getBoundingClientRect();
          const scrollLeft = this.navigationNode.scrollLeft;
          this.setState({
            pointer: {
              top: `${nav.height}px`,
              left: `${(label.left + scrollLeft) - nav.left}px`,
              width: `${label.width}px`,
            },
          });
        });
      }
```

### TO
```js
    updatePointer = (idx) => {
      const navigationNode = this.navigationNode
      if (navigationNode && navigationNode.children[idx]) {
        requestAnimationFrame(() => {
          const nav = navigationNode.getBoundingClientRect();
          const label = navigationNode.children[idx].getBoundingClientRect();
          const scrollLeft = navigationNode.scrollLeft;
          this.setState({
            pointer: {
              top: `${nav.height}px`,
              left: `${(label.left + scrollLeft) - nav.left}px`,
              width: `${label.width}px`,
            },
          });
        });
      }
```

**Comment by bionikspoon** [comment]
Tried out that code snippet locally in my project.  Turns out, it solves one problem but reveals another!  It's running `setState` on an unmounted component!! :)  I added more code to check if the component is mounted before setting state.  Went ahead and created a pr with all my local changes.

**Comment by binhqx** [comment]
#1604 may also be a fix for it

**Comment by javivelasco** [comment]
This should be solved by #1604! Otherwise we will reopen

**Comment by bionikspoon** [comment]
Sounds good.

**Comment by jodonnell** [comment]
we are still getting this error after merging 1604.  seems to me like you might just want to put an if this.navigationNode before this.navigationNode.getBoundingClient, but I only understand the code superficially.

**Comment by javivelasco** [comment]
I think it's not released @jodonnell . I'm releasing a new version that should cover the fix

**Comment by jodonnell** [comment]
yes, we have forked react toolbox and pulled that commit in, still seeing the same issues.

**Comment by bionikspoon** [comment]
I wonder if there's anyway to write a test for this

**Comment by Chengwen** [comment]
Hi @javivelasco , we got the same error when using Tabs component. Do you have any plan of release a new version with this fix? Thank you!

**Comment by kbrownhbs** [comment]
I am having the same issue.

**Comment by rokoroku** [comment]
It should be reopened. still exists on `2.0.0-beta.12`

**Comment by anissaSanadtech** [comment]
I am having the same issue

**Comment by danieljodeci** [comment]
Any updates on this? Still receiving this error using the Tabs component.

**Comment by rokoroku** [comment]
This library seems to be unmaintained, but for those who suffer from this issue I share my silly workaround here:

```jsx
<Tabs
  innerRef={(ref) => {
    if (ref && !ref.__patched) {
      ref.__patched = true;
      ref.updatePointer = (idx) => {
        const _this = ref;
        _this.updatePointerAnimationFrame = window.requestAnimationFrame(() => {
          if (_this.navigationNode && _this.navigationNode.children[idx]) {
            const nav = _this.navigationNode.getBoundingClientRect();
            const label = _this.navigationNode.children[idx].getBoundingClientRect();
            const scrollLeft = _this.navigationNode.scrollLeft;
            _this.setState({
              pointer: {
                top: nav.height + 'px',
                left: label.left + scrollLeft - nav.left + 'px',
                width: label.width + 'px'
              }
            });
          }
        });
      };
    }
  }}
>
  {...}
</Tabs>
```

This may work on `2.0.0-beta.12`.
