### ISSUE TITLE
Input element label glitch

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#171]
If you have an Input element and don't bind the value property, the label doesn't stay in place if the input field blurs while there's text in it:

![input label](https://cloud.githubusercontent.com/assets/1678/11432279/b56e056a-9478-11e5-96be-8b109d4c64a1.gif)

**Comment by soyjavi** [comment]
We will fix ASAP

**Comment by javivelasco** [comment]
@alltom that's the expected behavior. The component is stateless which means that you need to pass a value always and update this value with the `onChange` callback. In the scenario you are reporting, the actual `input` element holds a value in the DOM, but the value `prop` is evaluated to `undefined`. Since the input doesn't have a value, the label is placed in the center.

We made it that way because with this approach you don't need to synchronize properties and state.
Thanks! :)

**Comment by alltom** [comment]
FYI, the inconsistency is pretty surprising as a user:

Tag | Controlled | Uncontrolled
--- | --- | ---
`<input>` | works | works
`<Input>` with no label | works | works
`<Input>` with a label | works | doesn't work

**Comment by javivelasco** [comment]
I get your point but in which scenario would you use an input without passing a value?

**Comment by alltom** [comment]
For me, it's a search field (like in my GIF :). There's never any reason for me to set a new value, or to validate what the user has typed, so I don't bind the value property.

**Comment by javivelasco** [comment]
Yeah, I understand. Even for your use case, you are retrieving the changed value from the `onChange` handler so IMO you should store it somewhere and pass it back to the input. That allows to keep data always out of the components which is the best practice. Anyway, for cases like yours, we are going to take a look on the input and see if we can keep the label up when there is value in the `input` but not passing it through the props. 

More opinions here are very welcome :)

**Comment by alltom** [comment]
You've written way more React than I have, so please bear with me. Are you saying this isn't idiomatic? This seems like it keeps data out of the component by only exposing it with `onSearchQueryChange`:

    import React from 'react';
    import Input from 'react-toolbox/lib/input';

    export default (props) => {
      return <Input type='search' label='Search' onChange={onQueryChange} />;

      function onQueryChange(e) {
        props.onSearchQueryChange && props.onSearchQueryChange(e.target.value);
      }
    };

It seems like it gets more complicated if I have to turn this into a stateful component.

**Comment by javivelasco** [comment]
The purpose is not to have a stateful component but to be able to delegate the store wherever you want. For example, imagine you have an `Input` that holds a value but this value can be changed from outside. Typically you'd have a store holding the value and here I'm thinking about a `Form` that can be restored to initial values or something similar.

If you want to restore an Input you should be able to modify the value of the input by passing a `value` prop. If we store the state inside the component it is not possible to do it in an easy way. Yes, we can hook to `componentWillReceiveProps` but it means store duplication at the end. In this case the most flexible behavior is to extract all the state out of the component so if you want to create a component with state you can do it, and without state it's possible too.

What I do agree with you is that if the component is able to hold a value in the HTML `input` element, the label should behave accordingly, we need to review that. Anyway, this is quite opinionable so more feedback would be great.

**Comment by alltom** [comment]
Ah, thanks for the explanation. I think I get what you're saying. If I understand correctly, in my example, you'd recommend binding value to a property, to force the parent to deal with the mutation instead of handling it silently.

**Comment by javivelasco** [comment]
Exactly, also the new version will take as first argument for the callback the new value instead of the event. So your example would work like this:

```jsx
import React from 'react';
import Input from 'react-toolbox/lib/input';

class Search extends React.Component {
  state = { value: '' };

  handleChange = (value) => {
    this.setState({value})
  };

  render () {
    return (
      <Input 
        type='search' 
        label='Search' 
        value={this.state.query} 
        onChange={this.handleChange} 
     />;
    );
  }
};
```

Remember there is no need to create a stateful component if you are using a store. For example with Redux you'd subscribe your component to the store using a higher order component.

**Comment by ipsips** [comment]
i get the same label glitch if i use

`<Input type="number" label="Order" value={0} onChange={val => console.log(val)}/>`

![screen shot 2016-03-18 at 11 52 22](https://cloud.githubusercontent.com/assets/1770542/13874405/5d8a5e76-ed00-11e5-9386-891a4e273554.png)

**Comment by ipsips** [comment]
ok, i now see this was fixed in the source just a few days ago. watching for a new release..

**Comment by FezVrasta** [comment]
I'm still having the problem with controlled inputs even if I manually set `floating` to true..
