### ISSUE TITLE
How can I restore scrollbars?

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#221]
commons.scss sets the height and width of `::-webkit-scrollbar` to 0, but I have a site with a lot of data where invisible scrollbars are a hindrance. I've been unable to find a way to override this style, though. Is it possible?

**Comment by javivelasco** [comment]
Yes, there is an open issue about this and we are going to change it for the next release.
Problem is that this is defined as a generic style. No worries we are suppressing it. Working on it during the weekend I had a quite busy week.

**Comment by javivelasco** [comment]
I've just add to dev some commits to remove scrollbars only in specific places. It should fix this!

**Comment by alltom** [comment]
Great, thank you!

**Comment by BlaineBradbury** [comment]
how to restore scrollbars on the dropdown specifically... looks like it is still missing in the latest release

**Comment by mankim** [comment]
Is there way to enable scroll on ButtonGroup/DropdownButton?

**Comment by Doff3n** [comment]
Scrollbars are visible on IE11 in the dropdowns, but are not working correctly. When you use the scrollbar with the mouse
