### ISSUE TITLE
Dynamically created/selected tab incorrectly styled

### ISSUE THREAD

**Issue by Bjvanminnen** [react-toolbox/react-toolbox#290]
I have a simple component in which when you click on the last tab, it creates a new tab and selects in. When doing so, the little line beneath the tab showing which ones is active appears to be the length of the old label rather than the new one. Here are some screen shots:

Original state
![screen1](https://cloud.githubusercontent.com/assets/1767466/12741396/c0dd6e76-c930-11e5-910a-7fb35fe2036c.png)

I click the + to create a new tab. The line beneath it is too short
![screen2](https://cloud.githubusercontent.com/assets/1767466/12741397/c0de19de-c930-11e5-8e23-737bbad78f70.png)

Now I click the "Shorty" tab, and the line expands to fit as expected.
![screen3](https://cloud.githubusercontent.com/assets/1767466/12741398/c0df1f6e-c930-11e5-9787-b53dd3557233.png)

The code for my component:
```
class TabTest extends React.Component {
  constructor(props) {
    super(props);

    this.handleTabChange = this.handleTabChange.bind(this);

    this.state = {
      index: 0,
      tabs: ['LONG TAB HERE']
    };
  }

  handleTabChange(index) {
    if (index === this.state.tabs.length) {
      this.setState({
        tabs: this.state.tabs.concat('Shorty')
      });
    }
    this.setState({index});
  }

  render() {
    return (
      <Tabs index={this.state.index} onChange={this.handleTabChange}>
        {this.state.tabs.map((tab, index) => (
          <Tab key={index} label={tab}>{tab}</Tab>
        ))}
        <Tab label="+"></Tab>
      </Tabs>
    );
  }
}

**Comment by javivelasco** [comment]
I think this is happening because the size of the element should be calculated when state changes. Try to add a small delay to check if it works. Although it's not the perfect solution it may do the workaround while we try to find a better solution

**Comment by Bjvanminnen** [comment]
FWIW, setting the index inside a 1s `setTimeout` does seem to function as a temporary workaround

**Comment by javivelasco** [comment]
Then it's something else we need to investigate

**Comment by javivelasco** [comment]
Solved with a timeout, but it should be applied when the position is calculated. This is a recurring issue with react updates + get bounding rect

**Comment by neverfox** [comment]
Something is still not right, even without the dynamic case. When tabs load initially, the pointer is too long. Only after the first click does the pointer size correctly. I tried this with the TabsTest example from the docs.

**Comment by neverfox** [comment]
It works with a longer setTimeout (around 200. for me). However, as you probably already know, this is a pretty brittle solution, as it might be highly dependent on circumstances.
