### ISSUE TITLE
unable to style input child of autocomplete

### ISSUE THREAD

**Issue by t22james** [react-toolbox/react-toolbox#920]
this seems similar to this previous ticket:
https://github.com/react-toolbox/react-toolbox/issues/674
In v1.1.2 I am able to pass theme={theme} to DatePicker, and the nested Input (including labels, errors etc) also receives all of the themed classes (even though i can't see it explicitly passing it down as a prop). I expected the same thing to occur with Autocomplete, but it does not. The nested Input (including labels, errors etc) doesn't receive the theme despite same syntax/prop. Could both of these elements (and any others that nest an Input) perhaps have an inputTheme prop added, to explicitly pass desired full theming abilities down into the input (including labels, errors etc)?

**Comment by t22james** [comment]
https://github.com/react-toolbox/react-toolbox/issues/877
potentially duplicate, but that ticket only specifies 'label'. I'd like entire Input (i.e. with all children) exposed to a theme, so i can normalise with my standard Input fields.

**Comment by rubenmoya** [comment]
Yep, probably adding `className={classnames(this.props.theme.input, {[inputClassName]: inputClassName })}` to the autocomplete Input (same as DatePicker) will solve it, since you could use `.input {}` in your theme.

**Comment by javivelasco** [comment]
Fixed. You can write classNames to theme the `Input` component namespaced under `input` keyword. Check the readme in `Autocomplete`!

**Comment by t22james** [comment]
@javivelasco ok finally uncovered what you mean by reading the readme file in the 1.2.5 Autocomplete folder itself rather than online. This still doesn't seem to work as well as the method above, but understand you must have reasons for doing so, to do with namespacing etc. 

There is further confusion currently in that the current version, 1.2.5 on npm seems to contain /lib files which don't match the /components, so anyone running react-toolbox from npm will not be getting that functionality by default.

Finally, if this is going to be the chosen method for handling nested styles, then Dropdown and Datepicker should also receive the same support?

**Comment by javivelasco** [comment]
Sor sure. There are components that need to be updated with this approach too. It's relatively new and not implemented in react toolbox but it's very handy. I'm going to run the build and deploy during the next days to keep everything updated!

**Comment by stereokai** [comment]
@javivelasco @t22james I was having a hard time coping with theming in react-toolbox and I thought I could add some information because the explanation of this feature is quite unclear:

> ### Theme
>
> This component uses an `Input` under the covers. The theme object is passed down namespaced under `input` keyword. This means you can use the same theme classNames from `Input` component but namespaced with `input`. For example, to style the label you have to use `inputLabel` className.

I think a practical example here would be of real help to beginners (like me):

If you want to style anything inside the `Input` component of a `Dropdown` or `Autocomplete` component, react-toolbox provides a way to reference class names inside `Input` from parent components such as `Dropdown` or `Autocomplete`.

To achieve this, you have to add the style rules for `Input` to the theme .scss file for the parent (`Dropdown` or `Autocomplete`). For example, I want to change the input element to the color white. Inside the `Input` component, the `<input>` element has a class name `.inputElement`. So to modify it from the theme of `Dropdown` or `Autocomplete`, we have to prefix the class name (in camel case) with `input`:

```scss
.inputInputElement {
  color: #fff;
  border-bottom-color: #fff;
}
```

Again, this should be copied to the theme file for the component containing `Input`, ie. `Dropdown` or `Autocomplete`, etc.

**Comment by javivelasco** [comment]
Yes I agree the docs are not complete on this regard. If you want to send a PR to master I'd be happy to release it :)

**Comment by stereokai** [comment]
I will.

@javivelasco also is there a reason that `theme` and `themeNamespace` attributes are missing from the input in the `date_picker` component?

**Comment by javivelasco** [comment]
Yes, they are missing because the implementation of the `themeNamespace` happened after the implementation of the Date Picker :) Just for that, it would be better to add it
